Repository abrensch/brouter, pull requests merged in 2022-10, with the labels that each got.

#464 Enable use of direction to app
  brouter-routing-app/src/main/aidl/btools/routingapp/IBRouterService.aidl
  brouter-routing-app/src/main/java/btools/routingapp/BRouterWorker.java
Labels: bug, android

#305 Update river profile
  misc/profiles2/river.brf
Labels: profiles

#469 Update jekyll/gh-pages dependencies
  docs/Gemfile
  docs/Gemfile.lock
Labels: dependencies
