Repository abrensch/brouter, pull requests merged in 2023-07, with the labels that each got.

#573 optimizing constant expressions in profile parsing
  brouter-core/src/main/java/btools/router/ProfileCache.java
  brouter-core/src/main/java/btools/router/RoutingContext.java
  brouter-expressions/src/main/java/btools/expressions/BExpression.java
  brouter-expressions/src/main/java/btools/expressions/BExpressionContext.java
  brouter-expressions/src/main/java/btools/expressions/ProfileComparator.java
  brouter-expressions/src/test/java/btools/expressions/ConstantOptimizerTest.java
  brouter-expressions/src/test/resources/profile_test.brf
Labels: enhancement

#581 Fixed error in single download
  brouter-routing-app/src/main/java/btools/routingapp/DownloadWorker.java
Labels: bug, android

#582 Add portrait mode to app
  brouter-routing-app/src/main/AndroidManifest.xml
  brouter-routing-app/src/main/java/btools/routingapp/BInstallerActivity.java
  brouter-routing-app/src/main/java/btools/routingapp/BInstallerView.java
Labels: enhancement, android
